### ISSUE TITLE
devel_themer requires unresolved dependency simplehtmldom

### ISSUE THREAD

**Issue by szeidler** [ramsalt/DrupalMakes#15]
In https://github.com/ramsalt/DrupalMakes/blob/master/dists/base/base-d7-modules.make the `devel_themer` module is included, but its dependency  `simplehtmldom` is not part of the platform.

Since we have `$conf['theme_debug']` in core, i would recommend to remove devel_themer from the platform.

**Comment by esolitos** [comment]
I agree on the removal, we can still download it manually if ever needed.
